### ISSUE TITLE
wrong fps in tracker.cpp

### ISSUE THREAD

**Issue by pauloord123** [spmallick/learnopencv#123]
Tracker.cpp gives fps values only for the tracker->update, not for video.read() + tracker->update.

Better start with `timer = (double)getTickCount(); ` just before the while(video.read) loop, and again at the end of that loop. Remove the timer from the first line in the loop.
This gives reasonable fps.

**Comment by asmorkalov** [comment]
It's frame rate of tracker algorithm.
