### ISSUE TITLE
advice for face morph

### ISSUE THREAD

**Issue by leoneckert** [spmallick/learnopencv#13]
Hello! Thanks for this amazing repo, so much to learn!!
I am writing a program based on the facemorph code. It works really nicely except one detail that I can't solve yet, but I feel it must be something really simple. The warped triangles seem to overlap by 1 pixel, and their pixel colour then wraps around 255 (as I assume) and I get these lines in between the pieces (view attached image). 
Any idea what would be a simple solution to that? Greatly appreciate you help!
Thanks
<img width="418" alt="screen shot 2017-03-18 at 14 11 00" src="https://cloud.githubusercontent.com/assets/14130931/24074750/107cf5bc-0be5-11e7-98cc-a798223422fb.png">

**Comment by leoneckert** [comment]
I tried to hack together a solution by adding a 127 grey line to the masks, but that's not a good solution....
<img width="702" alt="screen shot 2017-03-18 at 14 39 40" src="https://cloud.githubusercontent.com/assets/14130931/24074931/bafcd108-0be8-11e7-82bd-b7fa1b5c823c.png">

**Comment by leoneckert** [comment]
am I likely to have a rounding error somewhere? int vs float? I tried everything :D

**Comment by leoneckert** [comment]
:D :D i am glad you didn't reply yet, found the error myself and feeling oh so good. 
it was a typo that I could only find after understanding everything about masks that I didn't understand before -- I learned a lot. thanks and sorry for the many messages here!

**Comment by spmallick** [comment]
No problem! Glad that you figured it out yourself. I am traveling and so was not able to get back to you.

**Comment by conradhappeliv** [comment]
@leoneckert can you post what the problem/solution was? I am also having the same issue and I'd like to know how you fixed it. :tired_face:

**Comment by leoneckert** [comment]
@conradhappeliv I find it hard to believe you would do the exact same mistake, but as far as I remember I just mixed up the operators in the line below, using a "+" instead of a "*" in one spot... 
```
# Copy triangular region of the rectangular patch to the output image
img[r[1]:r[1]+r[3], r[0]:r[0]+r[2]] = img[r[1]:r[1]+r[3], r[0]:r[0]+r[2]] * ( 1 - mask ) + imgRect * mask
```
same problem?

**Comment by conradhappeliv** [comment]
@leoneckert Finally figured it out! It was similar but not the same. You were right that the masks were overlapping by a pixel. I just set each mask to 0 wherever image data was already in the output.
