### ISSUE TITLE
Yolo v3 in OpenCV 4.0.0 can run but cannot get any result

### ISSUE THREAD

**Issue by KobayashiLiu** [spmallick/learnopencv#149]
Hi, i ran the yolov3 model by opencv 4.0.0.It's about 8ms to compute the network,but cannot get any result with a rectangle.Is the 4.0 alpha'bug or the code somewhere has wrong ?

**Comment by Jeremy26** [comment]
Hello, check this and tell me if you have the same error as me : https://github.com/spmallick/learnopencv/issues/148
