### ISSUE TITLE
Finding extreme points in the contours

### ISSUE THREAD

**Issue by Kotresh17** [spmallick/learnopencv#158]
Hi, I want to find out the extreme points in the contours in c++. can you please help me with that am facing difficulties in finding out the extreme left, extreme right, extreme top and extreme bottom values.

**Comment by sturkmen72** [comment]
use [cv::boundingRect](https://docs.opencv.org/master/d3/dc0/group__imgproc__shape.html#gacb413ddce8e48ff3ca61ed7cf626a366)

**Comment by Kotresh17** [comment]
hey, thanks for the reply but I want convert this python code to c++ . 
    extLeft = tuple(c[c[:, :, 0].argmin()][0])
    extRight = tuple(c[c[:, :, 0].argmax()][0])
    extTop = tuple(c[c[:, :, 1].argmin()][0])
    extBot = tuple(c[c[:, :, 1].argmax()][0])

**Comment by Kotresh17** [comment]
hey thanks for the suggestion. I did using boundingRect, I got exact output which is needed.
