### ISSUE TITLE
OpenCV Version ???

### ISSUE THREAD

**Issue by anselal** [spmallick/learnopencv#16]
In which version of OpenCV are we suppose to run the examples ?

**Comment by leslie-wang** [comment]
I got same problem for Tracking example. It reports below error. I guess it is related with opencv version.

I'm using opencv 3.3, ubuntu 16.04

```
$ g++ -std=c++11 tracker.cpp 
tracker.cpp: In function ‘int main(int, char**)’:
tracker.cpp:20:41: error: ‘end’ is not a member of ‘std’
     vector <string> trackerTypes(types, std::end(types));
                                         ^
tracker.cpp:24:28: error: ‘create’ is not a member of ‘cv::Tracker’
     Ptr<Tracker> tracker = Tracker::create(trackerType);
```

**Comment by mufaawan** [comment]
I used OpenCV 3.2.0 to run this example inside windows. Working quite fine. Need any help? Write me here mufadeveloper@gmail.com.

**Comment by asmorkalov** [comment]
All C++ samples are aligned with OpenCV 4.x: https://github.com/spmallick/learnopencv/pull/446
