### ISSUE TITLE
huMoments not defined

### ISSUE THREAD

**Issue by yjdeveloper** [spmallick/learnopencv#212]
When I run huMoments.py code, I am getting 'huMoments' is not defined error. Can you tell why I am getting this error?

**Comment by vikasguptaiisc** [comment]
Are you using python2?

Use Python 3 or add `from __future__ import print_function` at the top of the code

**Comment by penkesiva** [comment]
Because the file doesn't exist. CMakeLists.txt is looking for huMoments and the file is named HuMoments.cpp (notice the upper case H)
