### ISSUE TITLE
Error in Text Detection EAST

### ISSUE THREAD

**Issue by slmanali** [spmallick/learnopencv#245]
frozen_east_text_detection.pb
 OpenCV(3.4.1) Error: Unspecified error (FAILED: fs.is_open(). Can't open "true") in cv::dnn::ReadProtoFromBinaryFile, file F:\WORK\opencv-3.4.1\modules\dnn\src\caffe\caffe_io.cpp, line 1126

**Comment by vikasguptaiisc** [comment]
You need to download the file and put it in the same folder as the code.
Download link https://www.dropbox.com/s/r2ingd0l3zt8hxs/frozen_east_text_detection.tar.gz?dl=1

**Comment by slmanali** [comment]
i downloaded it!
the problem in this line  Net net = readNet(model);
there is no function named "readNet"

**Comment by vikasguptaiisc** [comment]
Which opencv version are you using?

**Comment by slmanali** [comment]
OpenCV(3.4.1) bulid with cuda 8.0 and qt

**Comment by slmanali** [comment]
i used this function "readNetFromTensorflow" and get the error.

**Comment by vikasguptaiisc** [comment]
The same error or a different one?

**Comment by slmanali** [comment]
same error.
OpenCV 3.4.1. doesn't recognize function "readNet"

**Comment by vikasguptaiisc** [comment]
well, if you are using readNetFromTensorflow then how can it give this error. Please cross-check

**Comment by slmanali** [comment]
can you help me with command line that you use to run this project?

**Comment by slmanali** [comment]
when i use this command line 
"textDetection.exe --input=F:\WORK\LPR\newtraining\new_plates\test\ee1.jpg --model=frozen_east_text_detection.pb --width=320 --height=320  --thr=0.5  --nms=0.4 "
i get this error 
feature_fusion/Shape:Shape(resnet_v1_50/block4/unit_3/bottleneck_v1/Relu)
out_type:[ ]
T:0
OpenCV(3.4.1) Error: Unspecified error (Unknown layer type Shape in op feature_fusion/Shape) in cv::dnn::experimental_dnn_v4::`anonymous-namespace'::TFImporter::populateNet, file F:\WORK\opencv-3.4.1\modules\dnn\src\tensorflow\tf_importer.cpp, line 1582

**Comment by vikasguptaiisc** [comment]
I see. So this cannot be run using OpenCV 3.4.1. You'll need 3.4.3

**Comment by slmanali** [comment]
OK
thanks,

**Comment by zzcqinag** [comment]
opencv3.4.6
tensorflow1.14.0
 I get this error
error: (-2:Unspecified error) Can't create layer "feature_fusion/truediv" of type "RealDiv" in function 'getLayerInstance'
how can solve it? thank  you! @vikasgupta-github
