### ISSUE TITLE
Install script for rpi (both 3 and 4) contain wrong git checkout command

### ISSUE THREAD

**Issue by gerk59** [spmallick/learnopencv#258]
In the install scripts, for version 3.4 (that explicitly lists 3.4.4 as cvVersion), for git checkout the branch 3.4 is used, which leads to the most current version (3.4.5-dev) instead of 3.4.4.

The 4.0 version sets cvVersion to "master", but then explicitely checks out "master" instead of "$cvVersion".

I think it is wiser to use only one reference to a version of opencv, and $cvVersion looks like the right candidate,
this would make adopting the shell script for a new version a one-line change.

**Comment by vishwesh5** [comment]
Branch 3.4 contains the latest bug fixes and feature requests and that's why we are using that instead of `$cvVersion`.

**Comment by asmorkalov** [comment]
The script has been updated for the new post:
