### ISSUE TITLE
Suggested improvement to install scripts

### ISSUE THREAD

**Issue by gerk59** [spmallick/learnopencv#265]
Dear @vishwesh5 : in order to make version number more descriptive (and resistant to e.g. whitespace in version number):

1. Change $cvVersion to "$cvVersion"

2.  Update README.md for InstallScripts directory -> change 3.4.4 to 3.4.x.

since the 3.4 branch is evolving after version 3.4.4

**Comment by vishwesh5** [comment]
Hi @gerk59 
Thanks. Can you make the listed changes and create a PR for the same? Please tag me so that I can verify everything and merge it quickly.

Thanks
