### ISSUE TITLE
Wrong Claim Yolov3 is 9x faster on Opencv

### ISSUE THREAD

**Issue by mdv3101** [spmallick/learnopencv#273]
I have a 1050 TI and the python code which you have presented is giving me 4 FPS.
Stop spreading lies.

**Comment by vikasguptaiisc** [comment]
Where did you find this information? In our blogs, we have compared the speed on the CPU. You would obviously get higher speed on the GPU since opencv does not use GPUs.

**Comment by mdv3101** [comment]
https://www.reddit.com/r/computervision/comments/98t7j7/yolov3_using_opencv_is_9x_faster_on_cpu_compared/

**Comment by vikasguptaiisc** [comment]
It's clearly written that OpenCV is faster than DarkNet on CPU. Please read carefully before using harsh words on a public platform.

**Comment by mdv3101** [comment]
@vikasguptaiisc 
Such big claims in bold big fonts should mean something useful. Don't forget to add 4 FPS on CPU and that too using 4 CPU i7 cores. 

That post was unnecessary. Stop trolling.

**Comment by vikasguptaiisc** [comment]
We have mentioned that the code takes .22 seconds which is ~4.5 FPS? I really don't understand what the problem here is!

**Comment by spmallick** [comment]
Looks like this is settled. I am closing this.

**Comment by mdv3101** [comment]
@vikasguptaiisc 
Mention-> It is using 4 i7 8th generation cores.

This is called click baiting.
