### ISSUE TITLE
mapIdx values in Multi-Person-Pose Estimation

### ISSUE THREAD

**Issue by oloa** [spmallick/learnopencv#291]
@vikasguptaiisc @spmallick Hello, Thanks for the amazing blog post

While I was looking at the code for Multi-Person-Pose Estimation in [multi-person-openpose.py](https://github.com/spmallick/learnopencv/blob/master/OpenPose-Multi-Person/multi-person-openpose.py), and **I'm having trouble understanding the `mapIdx` variable** which comment says:

> #index of pafs correspoding to the POSE_PAIRS
> #e.g for POSE_PAIR(1,2), the PAFs are located at indices (31,32) of output, Similarly, (1,5) -> (39,40) and so on.
> mapIdx = [[31,32], [39,40], [33,34], [35,36], [41,42], [43,44],
>           [19,20], [21,22], [23,24], [25,26], [27,28], [29,30],
>           [47,48], [49,50], [53,54], [51,52],
>           [37,38], [45,46]]

I have few questions regarding, such at:
- Are these PAF values/indexes pairs of `mapIdx` variable that corresponding to `POSE_PAIR` values are just random numbers or derived from an equation or something similar? If yes, can you please tell the corresponding equation/algorithm.
- Secondly, what `mapIdx` significance in the given code? If i change `model` and the respective `prototxt` file with another pose-model from [**openpose**](https://github.com/CMU-Perceptual-Computing-Lab/openpose) such as `MPI`, How the values of `mapIdx` changes?

Please Help?

**Comment by HaritsNasution** [comment]
I'm also having trouble understanding where the mapIdx comes from aswell...
Is there an explanation about this already?
