### ISSUE TITLE
Pedestrian counter with two of lines

### ISSUE THREAD

**Issue by easternmie** [spmallick/learnopencv#3]
Hi,

I'm interested on Pedestrian Counter project with openCV. One of the sample source code that i've found is shared by @anandsinghkunwar on git hub https://github.com/anandsinghkunwar/pedestrian-counter

But it quite confusing on returning of function `line1(x,y)` and `line2(x,y)`. I want to change the default lines to be transverse over the frame to be like this:

```
    cv2.line(frame, (0,100), (500,100), (255, 0, 0), 2)
    cv2.line(frame, (0,200), (500,200), (255, 0, 0), 2)
```

Anybody can help me to tuning the function `line1(x,y)` and `line2(x,y)`

**Comment by Mayur-RD** [comment]
def line1(x,y):
    global m,line_start
    return y - m*x - line_start[1]

def line2(x,y):
    global m1,line_start1
    return y - m1*x - line_start1[1]

line_start=(0,100)
line_end=(500,100)
line_start1=(0,200)
line_end1=(500,200)
crossedAbove = 0
crossedBelow = 0
m=(line_end[1]-line_start[1])/(line_end[0]-line_start[0])
m1=(line_end1[1]-line_start1[1])/(line_end1[0]-line_start1[0])

**Comment by anandsinghkunwar** [comment]
I think @easternmie figured it out that day itself. Thanks for the clarification @Mayur-RD

**Comment by easternmie** [comment]
Thanks @Mayur-RD for your explanation. Yes, I figured it out as what @anandsinghkunwar mention.

**Comment by spmallick** [comment]
I am sorry, this question is not related to this repo.
