### ISSUE TITLE
Unrecognized or unsupported array type in function 'cvGetMat'

### ISSUE THREAD

**Issue by alexzen1997** [spmallick/learnopencv#305]
image = cv2.imread("00000.png")
(h, w) = image.shape[:2]
blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 1.0,
	(300, 300), (104.0, 177.0, 123.0), swapRB=True, crop=False)
cv2.imshow("Blob", blob)

I had this error after executing this code "Unrecognized or unsupported array type in function 'cvGetMat'" What should i do

**Comment by asmorkalov** [comment]
`blob` is not standard OpenCV image, but tt's array of floating point values prepared for DNN inference. `imshow` cannot show it as it's not image.
