### ISSUE TITLE
Problem when running Introduction to Semantic Segmentation 

### ISSUE THREAD

**Issue by changbaishan** [spmallick/learnopencv#330]
from torchvision import models
fcn = models.segmentation.fcn_resnet101(pretrained=True).eval()

------------------------------------------------------------------------
AttributeError                         Traceback (most recent call last)
<ipython-input-1-7476d3896e95> in <module>
      1 from torchvision import models
----> 2 fcn = models.segmentation.fcn_resnet101(pretrained=True).eval()

AttributeError: module 'torchvision.models' has no attribute 'segmentation'

Can you please give us an environment.yml to config?
Thank you very much for your wonderful github and posts.

**Comment by antithing** [comment]
Hi @changbaishan , I get the same error, did you manage to solve this? Thanks!

**Comment by changbaishan** [comment]
Not yet. let me know if you or someone else solve the problem. Thank you very much.

**Comment by Deep-Learner** [comment]
I had the same problem. I solved it by updating pytorch with:
` pip3 install torchvision -U`
My old version was 1.0.0, on version 1.2.0 it works fine.
