### ISSUE TITLE
Mask-rcnn appear to be broken

### ISSUE THREAD

**Issue by changbaishan** [spmallick/learnopencv#331]
test6/learnopencv/Mask-RCNN$ python3 mask_rcnn.py --video=cars.mp4
Traceback (most recent call last):
  File "mask_rcnn.py", line 167, in <module>
    postprocess(boxes, masks)
  File "mask_rcnn.py", line 91, in postprocess
    drawBox(frame, classId, score, left, top, right, bottom, classMask)
  File "mask_rcnn.py", line 54, in drawBox
    im2, contours, hierarchy = cv.findContours(mask,cv.RETR_TREE,cv.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

The same thing happened when I tried  python3 mask_rcnn.py --image=cars.jpg

May be this is also a case where the underlying api changed. An environment.yml file may be helpful.

Thanks again.

**Comment by manansaxena** [comment]
-change the mask_rcnn.py 
-at line 54 remove im2(because of the output of cv.findContours() )
-then it should work fine

**Comment by changbaishan** [comment]
Yes. Indeed. 
Thanks very much for your help, manansaxena.
