### ISSUE TITLE
learnopencv/app-seperation-semseg/Background-Change.py

### ISSUE THREAD

**Issue by garimss** [spmallick/learnopencv#349]
how to you save image? when I save, I get black image only.

**Comment by asmorkalov** [comment]
`cv.imwrite()` does it in OpenCV. Please ensure that the frame is not empty and data format is uint8, but not float. Documentation: https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce
