### ISSUE TITLE
Error Occured when trained the model for binary classification

### ISSUE THREAD

**Issue by bhrtkoli14** [spmallick/learnopencv#354]
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at C:\w\1\s\windows\pytorch\aten\src\THNN/generic/ClassNLLCriterion.c:94

**Comment by Kan630** [comment]
I had the same error.
The number of classes is wrong here :

`# Number of classes
num_classes = len(os.listdir(valid_directory))`

**Comment by xlabd** [comment]
Thank you for answering @Kan630 

We can close this issue @vikasgupta-github
