### ISSUE TITLE
Install OpenCV on windows 10 with visual studio 2013

### ISSUE THREAD

**Issue by rahul4310** [spmallick/learnopencv#355]
Hi ,
I want to install OpenCV on windows 10 with visual studio 2013. I don't know how to do that.
My choice of visual studio 2013 is because I had already installed cuda 8 on it for my geforce 820m graphics card and it was giving error for other versions of visual studio.
Any help would be appreciated.

**Comment by zhangqizky** [comment]
https://marcomuraresearch.wordpress.com/2015/04/16/install-opencv-visual-studio/
