### ISSUE TITLE
Update for OpenCV 4.0?

### ISSUE THREAD

**Issue by farzonl** [spmallick/learnopencv#366]
https://github.com/spmallick/learnopencv/blob/8fca2653ae1cfe55afa0d9657df26791db5d140e/Delaunay/delaunay.cpp#L66

I'm not sure if you revisit old posts, but if you do  I would suggest changing these to cv::FILLED and LINE_AA.

If you don't have the time and want the change I can do it or if that isn't something you are interested in I can close this issue.

**Comment by asmorkalov** [comment]
Already addressed in https://github.com/spmallick/learnopencv/pull/446/
