### ISSUE TITLE
compilation_c++_YOLO

### ISSUE THREAD

**Issue by Sinchiguano** [spmallick/learnopencv#368]
Hi everyone,

I have the following problem, I tried the python detection of Yolo and it works perfectly but when I want to try the c++ I have the following error:
object_detection_yolo.cpp:9:27: fatal error: opencv2/dnn.hpp: No such file or directory , this shows in the compilation stage.
I am using Anconda with python 3.5 in a virtual environment, plus the openCV-3.4.2 as it said in the requirements. I did not install the openCV from source in order to avoid the long and tedious job of installation.

Any help is welcome please,

Thanks
Cesar

**Comment by asmorkalov** [comment]
Python package provides just pre-built OpenCV with python bindings, but not development files for C++ like CMake configuration files or C/C++ headers. You have to build OpenCV from sources to work with C++ code.
