### ISSUE TITLE
Facedetecion using DNN with res10_300x300_ssd_iter_140000_fp16.caffemodel disappointing

### ISSUE THREAD

**Issue by Arno-v** [spmallick/learnopencv#393]

**Comment by Arno-v** [comment]
I tested this with the example in FaceDetectionComparison/face_detection_opencv_dnn.cpp modified to use high resolution stills. It fails to detect most faces. Changeing the confidence treshold will give many false postives. Is this model not suitable for high resolution stills?

**Comment by asmorkalov** [comment]
According to file name the model is designed for input 300x300. You need to downscale the image to expected resolution and apply proper prepossessing or apply the model to sub-images. The second approach allows to find smaller faces, but obviously cannot handle the big ones.
