### ISSUE TITLE
Install Script for Ubuntu 18.04 with GPU support

### ISSUE THREAD

**Issue by ajay443** [spmallick/learnopencv#402]
The current install script`installOpenCV-4-on-Ubuntu-18-04.sh` is using doesn't use CUDA support. Adding a script to support the CUDA installation of OpenCV 4 would be helpful.

**Comment by xlabd** [comment]
The installation scripts are for everyone's convenience. The script installs OpenCV with minimum requirements. If you want the CUDA support, you can make changes to your script.

You can find CUDA MAKE commands from here: https://github.com/opencv/opencv/blob/master/CMakeLists.txt
