### ISSUE TITLE
C++ Question

### ISSUE THREAD

**Issue by Anonassassin** [spmallick/learnopencv#408]
Hi,

Please help me out with this question as i am unable to solve it due to lack of resources

Sent this question from an android device

You are supposed to code software that manages Parking lots. Vehicles get parked in a Parking lot. Each vehicle has a registration number, manufacturer and model. Vehicle can either be a car or a bike. In addition to above attributes Car also has number Of doors.

Following is part Of the code used in the Software. 

Please go through it and answer the questions that follow:

```
#include "Vehicle. h"

class ParkingLot

public:

ParkingLot( int size);

//returns true if parking slot was available, false otherwise


bool park(Vehicle*);

Vehicle** getParkedVehicles();

int getNum_of_slots();

private:

int numof_slots;

Vehicle** parkedvehicle;

}


int main()

{

ParkingLot new ParkingLot(30);

car *corolla1 = new Car( "LOX 213", "Toyota","corolla", 4);

Bike* honda1 = new Bike("LED 2179", "Honda", "CD70");

fastParking->park(corolla1);

fastParking->park(honda1);

int num=fastParking->getNum_of_slots();

Vehicle ** vehicles= fastParking->getParkedVehicles();

for(int i=0; i<num; i++)
{

/*the display() method displays registration number, manufacturer and

model in case of bike and in case of car it displays all Of above as well

as number Of doors*/

if(vehicles[i]!=0)

cout<<"Parking sloy"<<i+1<<"has"<<vehicles[i]->display();

else

cout<<"Parking slot"<<i+1<<"is empty"<<endl;

}

return 0;

}
```

From the scenario and code given above, answer the following questions: 

i. Identify the classes needed other than ParkingLot 

ii. All parking lots need to know where their server is located, this information is common amongst all objects Of ParkingLot, how can we achieve this? 

iii. Identify any inheritance relationships 

iv. Identify any composition relationships 

v. Give the declarations of the classes, please note that it should not be possible to instantiate an Object Of Vehicle. 

vi. Implement the park method Of the ParkingLot class.

**Comment by xlabd** [comment]
We won't be able to solve you with this problem.

@vikasgupta-github we can close this issue.
