### ISSUE TITLE
 OpenCV(4.1.2) /io/opencv/modules/imgproc/src/drawing.cpp:2383: error: (-215:Assertion failed) points.checkVector(2, CV_32S) >= 0 in function 'fillConvexPoly'

### ISSUE THREAD

**Issue by Nitesh7085** [spmallick/learnopencv#428]

**Comment by asmorkalov** [comment]
`checkVector` function checks if Mat or vector satisfies the requirements. In your case `points` parameter of `fillConvexPoly` is empty or has wrong dimentions or data type. See docs: https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#a167a8e0a3a3d86e84b70e33483af4466
