### ISSUE TITLE
get error while runing make commond in AgeGender folder 

### ISSUE THREAD

**Issue by Ranjeetrk** [spmallick/learnopencv#467]
I get this error while runing commond **make** after **cmake .** 

![image](https://user-images.githubusercontent.com/31475498/89608106-cd090780-d891-11ea-92a7-5d512d28536e.png)

![image](https://user-images.githubusercontent.com/31475498/89608179-135e6680-d892-11ea-9477-f5ee7a9d56a0.png)

**Comment by asmorkalov** [comment]
It looks like your OpenCV instance is build on other host or for another version of Ubuntu. Please re-build OpenCV to fix the issue.
