### ISSUE TITLE
Getting error while running reconstructFace.py

### ISSUE THREAD

**Issue by vaibhav1721** [spmallick/learnopencv#50]
Reading model file pcaParams.yml
Traceback (most recent call last):
  File "/home/vaibhav/PycharmProjects/reconstructFace.py", line 51, in <module>
    sz = (int(sz[0, 0]), int(sz[1, 0]), int(sz[2, 0]))
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by spmallick** [comment]
Did you create the PCA model first?

**Comment by vaibhav1721** [comment]
problem solved sir, thanks
