### ISSUE TITLE
Undefined reference to cv::Subdiv2D::getTriangleList - faceAverage.cpp

### ISSUE THREAD

**Issue by Luca96** [spmallick/learnopencv#54]
Hi, i'm developing an android application about **Average Face**.

I have a cpp file based on `faceAverage.cpp` (https://github.com/spmallick/learnopencv/blob/master/FaceAverage/faceAverage.cpp) 
but when i compile the code, i get this error:
`Error:(154) undefined reference to 'cv::Subdiv2D::getTriangleList(std::__ndk1::vector<cv::Vec<float, 6>, std::__ndk1::allocator<cv::Vec<float, 6> > >&) const'`

The error occur inside the *calculateDelaunayTriangles* function, precisely at this statement: `subdiv.getTriangleList(triangleList)`

The *calculateDelaunayTriangles* function is exactly the same as in  `faceAverage.cpp` 

How can i fix the error?

**Comment by alexander-zou** [comment]
I am desperate with the same problem in my android project, may I ask how did you solve it? Thank you so much!

**Comment by Luca96** [comment]
Hi  @alexander-zou, maybe your problem is about the standard c++ library. 
What i mean is that OpenCV use the `gnustl_shared` standard library, so if you don't use this library in your android project, the compiler will complain with every methods that has string or vector as argument.

If you use CMake you can add this snippet in your build.gradle under `android->defaultConfig`:
```java
externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -fexceptions"
                abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'  //keep only supported arch by your app
                arguments "-DANDROID_PLATFORM=android-15",  // change with your min api level
                        "-DANDROID_TOOLCHAIN=clang",
                        "-DANDROID_STL=gnustl_shared", // the standard lib
                        "-DANDROID_CPP_FEATURES=rtti exceptions"
            }
        }
```
and in your `CMakeLists` you have to add something like this:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fexceptions -std=gnustl")`

that is, i hope it works!

**Comment by Luca96** [comment]
Maybe you can try to recompile OpenCV with `libc++` instead of `gnustl`.

**Comment by calicratis19** [comment]
@Luca96 your previous comment worked for me finally. This was indeed an issue with gnu and libc++ stl. But I had to modify this
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fexceptions -std=gnustl")`

to

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fexceptions -std=gnu++11")`
