### ISSUE TITLE
Error : <class 'cv2.FileStorage'> returned a result with an error set 

### ISSUE THREAD

**Issue by sg7801** [spmallick/learnopencv#615]

**Comment by brmarkus** [comment]
Can you provide more details, please?
Which code, with demo, which sample were you running into the problem with?
Could you share at least a code-snippet?
Which result specifically did you get?

**Comment by sg7801** [comment]
The issue was resolved after I chose smaller dataset of 200 images from CalebA Dataset. Earlier I was using around 2000 images to train but after I reduced the size to 200 images which eventually reduced size of pcaParams.yml, the issue didnt pop up!
