### ISSUE TITLE
Gait Analysis

### ISSUE THREAD

**Issue by ritzdevp** [spmallick/learnopencv#67]
One can also use open pose estimation for gait analysis. Gait energy image is also a good technique.

**Comment by mauckc** [comment]
Gait energy image? Does that somehow calculate the mechanical potential and kinetic energy of the gait (coordinates of leg points) in 3D?

**Comment by ritzdevp** [comment]
Gait energy image is the resultant of a function applied on a series of segmented images of the gait of a person. Here: " https://pdfs.semanticscholar.org/33f6/4132ab2eefb61681dcd75186cdfaafa93c89.pdf "
Points obtained through open pose estimation can be used for gait analysis by analyzing the movement of all points of different individuals. And classifying these individuals on the basis of the pattern of the movement of points.
