### ISSUE TITLE
cannot get the tri.txt

### ISSUE THREAD

**Issue by xbnz-1997** [spmallick/learnopencv#670]

**Comment by xbnz-1997** [comment]
Hello,
I am trying to maoph 2 pictures from my own,
I read your blog post[https://learnopencv.com/face-morph-using-opencv-cpp-python/](url).
Howerver, I don't know how to get the tri.txt by performing [Delaunay Triangulation](https://learnopencv.com/delaunay-triangulation-and-voronoi-diagram-using-opencv-c-python/).
I appreciated for your help.

**Comment by brmarkus** [comment]
Your referenced article says these:

> But it is very easy to find a few point correspondences. For morphing two dissimilar objects, like a cat’s face and a human’s face, we can click on a few points on the two images to establish correspondences and interpolate the results for the rest of the pixels.

As well as using Facial-Landmark-detection:

> I used [dlib](http://dlib.net/) to detect 68 corresponding points. Next, I added four more points ( one on the right hand side ear, one on the neck, and two on the shoulders ). Finally, I added the corners of the image and half way points between those corners as corresponding points as well. Needless to say, one can add a few more points around the head and neck to get even better results, or remove the manually clicked points to get slightly worse ( but fully automatic ) results.

And then, referring to the Delaunay Triangulation article, you call `subdiv.getTriangleList()` and store the list in the file. (or keep it in memory and continue with the morphing).

**Comment by xbnz-1997** [comment]
Thanks.
