### ISSUE TITLE
PyTorch-ONNX-TensorRT-CPP Doesn't compile TensorRT 8.2

### ISSUE THREAD

**Issue by DaveBGld** [spmallick/learnopencv#673]
At line 144 of trt_sample.cpp :

    TRTUniquePtr<nvinfer1::INetworkDefinition> network{builder->createNetwork()};
`

`error: ‘class nvinfer1::IBuilder’ has no member named ‘createNetwork’; did you mean ‘createNetworkV2’?
[build]   144 |     TRTUniquePtr<nvinfer1::INetworkDefinition> network{builder->createNetwork()};`

Changed to 
`    TRTUniquePtr<nvinfer1::INetworkDefinition> network{builder->createNetworkV2(0U)};
`

And the model cannot be loaded at line 148

`    if (!parser->parseFromFile(model_path.c_str(), static_cast<int>(nvinfer1::ILogger::Severity::kINFO)))
    {
        std::cerr << "ERROR: could not parse the model.\n";
        return;
    }
`

Getting error

`[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format onnx2trt_onnx.ModelProto: 1:9: Message type "onnx2trt_onnx.ModelProto" has no field named "version".`

**Comment by KaiserW** [comment]
Since the "resnet50.onnx" in the repository is a LFG pointer rather than a real onnx file, you need `git lfs pull` or execute the python script "pytorch_model.py" in the same directory before running this CPP program.

**Comment by DaveBGld** [comment]
Thanks!
