### ISSUE TITLE
yolov5 c++ problem

### ISSUE THREAD

**Issue by shahla-ai** [spmallick/learnopencv#690]
hi all,
i trained a yolov5s model on my custom single class dataset and it worked just fine on yolov5-master 
i converted it to .onnx format to use on OpenCV framework , the python sample worked great but the c++ sample (yolov5.cpp) gave me a lot of detections that are not logical , and in some images gives the following error "Floating point exception (core dumped)"
note that the pre-trained yolov5s on coco works fine on .cpp sample when converted to .onnx ,but my custom model does not
any help?

**Comment by brmarkus** [comment]
Can you provide any details about your model, how you trained it, how you converted it, examples of input- and output-images? Could you even share your model?
Have you done any changes to the source-code, how have you used it, using which command-line?
Are you sure the C++ sample (which sample, which sub-folder?) performs the Non-Max-Suppression algorithm? Do both, the Python-code and the C++ code use the same command line parameters, maybe one uses default-values for some parameters where the other does not.

**Comment by shahla-ai** [comment]
hi @brmarkus 
i trained my custom model on a single class dataset to detect passanger planes using yolov5-master github code and using the following command : `python train.py --data data/pass-plane.yaml --weights yolov5s.pt --img 640 --epochs 230 --batch-size 16 --device 0`
it resulted in best.pt in the runs/train/exp/weights folder which i tested on yolov5-master and it worked very good

i converted best.pt into best.onnx using export.py script : `python export.py --weights best.pt --include onnx --data data/pass-plane.yaml --device 0 --imgsz 640 640
`
i used the samples found in https://github.com/spmallick/learnopencv/tree/master/Object-Detection-using-YOLOv5-and-OpenCV-DNN-in-CPP-and-Python , without any changes except change the name of the model to 'best.onnx' and the .names file to 'plane.names' the results are as shown below, and both samples have the same parameters

**yolv5.py**

![result](https://user-images.githubusercontent.com/72201377/174247139-77a32603-dd78-4933-8850-bf0366c9bdb0.jpg)

**yolov5.cpp**

![result-cpp](https://user-images.githubusercontent.com/72201377/174247671-c944ffa3-9550-4a72-ac67-0e63f864ac33.jpg)

**yolov5.cpp using yolov5s.onnx converted from yolov5s.pt pre-trained on coco**

![result-cpp](https://user-images.githubusercontent.com/72201377/174248770-e0c03b59-e589-4a25-8170-d86fd19de0da.jpg)

note that i'm using opencv 4.5.5

**Comment by shahla-ai** [comment]
The issue is solved finally !!
when testing on single class we should change:
`// Jump to the next column `
`data += 85;`
into 
`// Jump to the next column`
`data += 6;`
