### ISSUE TITLE
FaceAvereage - faces not morphing?

### ISSUE THREAD

**Issue by edent** [spmallick/learnopencv#7]
When I run `python faceAverage.py` I get this rather confused output.

![faceaverage](https://cloud.githubusercontent.com/assets/837136/16878496/ace946d8-4aa4-11e6-99cd-d8f6a1f223e5.png)

Running the `faceMorph.py` does seem to work. 

I'm running Python 2.7.6 on Ubuntu 14.04.4.  Any idea what's going wrong?

**Comment by spmallick** [comment]
This was resolved.
