### ISSUE TITLE
Can't open file: 'data/stereo_rectify_maps.xml' in read mode / !_map1.empty() in function 'cv::remap'

### ISSUE THREAD

**Issue by aaronlsmiles** [spmallick/learnopencv#758]
When running either [disparity2depth](https://github.com/spmallick/learnopencv/blob/master/Depth-Perception-Using-Stereo-Camera/python/disparity2depth_calib.py) or [obstacle_avoidance](https://github.com/spmallick/learnopencv/blob/master/Depth-Perception-Using-Stereo-Camera/python/obstacle_avoidance.py) files, I get the same xml file read and remap errors at both [rectification](https://github.com/spmallick/learnopencv/blob/master/Depth-Perception-Using-Stereo-Camera/python/disparity2depth_calib.py#L84) [lines](https://github.com/spmallick/learnopencv/blob/master/Depth-Perception-Using-Stereo-Camera/python/obstacle_avoidance.py#L109).

```
[error:0@2.333] global D:\a\opencv-python\opencv-python\opencv\modules\core\src\persistence.cpp (505) cv::FileStorage::Impl::open Can't open file: '../data/stereo_rectify_maps
.xml' in read mode
[error:0@2.336] global D:\a\opencv-python\opencv-python\opencv\modules\core\src\persistence.cpp (505) cv::FileStorage::Impl::open Can't open file: '../data/depth_estimation_pa
rams_py.xml' in read mode
Traceback (most recent call last):
  File "C:\Users\XXXXXXXXXX\ObstacleAvoidSystem\Depth-Perception-Using-Stereo-Camera\disparity2depth_calib.py", line 84, in <module>
    Left_nice= cv2.remap(imgL_gray,
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:1703: error: (-215:Assertion failed) !_map1.empty() in function 'cv::remap'
```

Can anyone suggest anything, please?

I've tried using different methods like cv2.FileStorage.open (filename, flags) but I get similar errors. I've also tried to open in write mode and got a similar error. Any help would be great!

**Comment by brmarkus** [comment]
Are you sure the file exists?
If the file exists in the file-system and the relative path is correct (you might be in a different current-working-dir CWD and then the relative path isn't correct anymore: `"../data/stereo_rectify_maps.xml"`) - can you open the file with any other tool?

This is the referenced file:
https://github.com/spmallick/learnopencv/blob/master/Depth-Perception-Using-Stereo-Camera/data/stereo_rectify_maps.xml
I can display it even in the browser:

```
<?xml version="1.0"?>
<opencv_storage>
<Left_Stereo_Map_x type_id="opencv-matrix">
  <rows>480</rows>
  <cols>640</cols>
  <dt>"2s"</dt>
  <data>
    -25 -5 -24 -5 -23 -5 -22 -5 -21 -5 -20 -5 -19 -5 -18 -5 -17 -5 -16
    -5 -15 -5 -14 -5 -13 -5 -12 -5 -11 -5 -10 -5 -9 -5 -8 -5 -7 -6 -6 -6
    -5 -6 -4 -6 -3 -6 -2 -6 -1 -6 0 -6 1 -6 2 -6 3 -6 4 -6 5 -6 6 -6 7
    -6 8 -6 9 -6 10 -6 11 -6 12 -6 13 -6 14 -6 15 -6 16 -6 17 -6 18 -6
    19 -6 20 -6 21 -6 22 -6 23 -6 24 -6 25 -5 26 -5 27 -5 28 -5 29 -5 30
... ...
```
It doesn't look like you would need to have "git-lfs" installed locally on your machine as the referenced file is huge (7.5MB?), the file is directly part of the repo.

**Comment by aaronlsmiles** [comment]
Yeah the file exists and I can open it in other tools and read the contents similar to the original file.

**Comment by brmarkus** [comment]
Can you double-check the current-working-directory CWD, please?
From where you start your application - is the relative path `"../data/stereo_rectify_maps.xml"` still valid?
Do you call your application from within a script - which maybe spawns a new shell? Or your application changes the CWD?

**Comment by aaronlsmiles** [comment]
Hey thanks @brmarkus it was an issue with the CWD. Appreciate the help! Cheers 👍

**Comment by ZalvinZ** [comment]
Hi @aaronlsmiles I'm having the same issue. How did you end up solving this issue?

**Comment by brmarkus** [comment]
Can you check if you have the file locale "somewhere" below the repo's root folder?

@ZalvinZ can you confirm it is about this file of this project:

https://github.com/spmallick/learnopencv/tree/bfa948fff83c80a9e6e5885410098060f196a1c4/Depth-Perception-Using-Stereo-Camera/data
