### ISSUE TITLE
Add the code for Volume Control using Hand Gestures Recognition

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [spmallick/learnopencv#789]

**Comment by brmarkus** [comment]
Is this a request ;-) ?

There are so many posts and videos about it already, e.g.:

https://www.section.io/engineering-education/creating-a-hand-gesture-volume-controller-using-python-and-pycharm/
https://www.youtube.com/watch?v=mkKM_EXVtbk
https://www.youtube.com/watch?v=9iEPzbG-xLE
https://www.youtube.com/watch?v=9ZRqc4EaPRU
https://www.youtube.com/watch?v=dqfm5P5iQoQ
