### ISSUE TITLE
How to generate the facial landmark text file?

### ISSUE THREAD

**Issue by crosofg** [spmallick/learnopencv#8]
I see you have used txt files for image facial coordianates. How did you generate those? I am not able to iterate over the predictor function of the dlib? Can you please share the code snippet?

**Comment by mikeyny** [comment]
@crosofg If you mean the haar cascade classifier xml file ,here is how to generate your own [train haar cascade](http://coding-robin.de/2013/07/22/train-your-own-opencv-haar-classifier.html) , you can also download them [here](https://github.com/opencv/opencv/tree/master/data/haarcascades)

**Comment by bababash** [comment]
@mikeyny I don't think that's the answer. For every image included in the repo there's a txt file with coordinates. If we want to use our own image, how do we generate that file?

**Comment by spmallick** [comment]
Here you go. 
https://github.com/spmallick/dlib/blob/master/examples/face_landmark_detection_to_file.cpp
